import React, { useState } from "react";
import image3 from "../../../public/assets/image10.png";
import Image from "next/image";
import Niv from "@/components/niv";
import Swal from "sweetalert2";
import axios from "axios";

function Home() {
  const [file, setFile] = useState<File | null>(null);
  const [input, setInput] = useState<string>("");
  const [imagePath, setImagePath] = useState<string>(""); // State for output image

  const handleSubmit = async () => {
    if (file) {
      const formData = new FormData();
      formData.append("file", file);

      Swal.fire({
        title: "Processing...",
        html: 'Please wait while the data is being processed.<br><div class="spinner-border" role="status"></div>',
        allowOutsideClick: false,
        showCancelButton: false,
        showConfirmButton: false,
        didOpen: () => {
          Swal.showLoading();
        },
      });

      try {
        const response = await axios.post(
          // "http://127.0.0.1:5000/upload",
          "https://deepfakeimagetext-830359766867.us-central1.run.app",
          formData,
          {
            headers: {
              "Content-Type": "multipart/form-data",
            },
          }
        );
        if (response.status === 200) {
          setInput(response.data.result);
          setImagePath(response.data.output_image_path); // Path to output image

          Swal.fire({
            title: "Uploaded Successfully!",
            text: "Your file has been uploaded and processed.",
            icon: "success",
            confirmButtonText: "OK",
          });
        }
      } catch (error) {
        console.error("Error uploading file:", error);

        Swal.fire({
          title: "Upload Failed!",
          text: "Something went wrong while uploading the file.",
          icon: "error",
          confirmButtonText: "Try Again",
        });
      }
    }
  };

  const handleFileChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    if (event.target.files && event.target.files[0]) {
      const selectedFile = event.target.files[0];
      setFile(selectedFile);
    }
  };

  const handleClear = () => {
    setFile(null);
    setInput("");
    setImagePath("");
    window.location.reload();
    Swal.fire("Cleared", "The text and AI result have been cleared.", "info");
  };

  return (
    <div>
      <Niv />
      <div className="flex  p-4">
        <div className="flex flex-col lg:flex-row w-full max-w-8xl  ">
          <div className="w-1/2 flex flex-col justify-center px-8 py-12 mt-5 ">
            <h2 className="text-orange-500 text-3xl font-bold mb-8">
              Image Verification: Check Authenticity
            </h2>

            <b className="text-1.5xl me-5">
              "Upload an image and let AI verify its origin."
            </b>

            <div className="card w-96 flex-grow me-3 relative">
              <p>
                "Wondering if an image is real or generated by AI? Simply upload
                the image, and our advanced AI algorithms will analyze its
                features to determine its authenticity. Whether you're dealing
                with altered photos, AI-generated visuals, or genuine content,
                our system provides quick, reliable results, helping you stay
                informed and avoid misinformation."
              </p>
            </div>
          </div>
          <div className="flex justify-center  lg:w-1/2 w-full mb-8 lg:mb-0">
            <div>
              <div className="card bg-neutral-600 rounded-box h-[300px] flex-grow me-3 relative mt-[50px]">
                <Image
                  className="  lg:w-[500px] p-5"
                  src={image3}
                  alt="Your Company"
                />
              </div>
              <input
                type="file"
                className="file-input file-input-bordered bg-blue-900 text-white w-full   rounded mt-5"
                onChange={handleFileChange}
              />
              <div className="flex gap-2 mt-5">
                {file && (
                  <button
                    className="bg-blue-900 text-white w-full font-bold py-2 px-4 rounded"
                    onClick={handleSubmit}
                  >
                    Submit
                  </button>
                )}
                <button
                  className="bg-red-600 text-white w-full font-bold py-2 px-4 rounded"
                  onClick={handleClear}
                >
                  Clear
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="card border border-orange-500 bg-orange-100 border-[3px] rounded-box h-[150px] flex-grow  m-5">
        <b className="text-1.5xl m-5">"AI verifies Result:"</b>
        <div className="text-center">{input}</div>
      </div>

      {/* Display Output Image */}
      {imagePath && (
        <div className="card border border-orange-500 bg-orange-100 border-[3px] rounded-box h-[500px] w-[500px] flex-grow  m-5">
          <b className="text-1.5xl m-5">Processed Image:</b>
          <div className="text-center">
            <img
              src={`http://127.0.0.1:5000/${imagePath}`} // Ensure this URL works correctly
              alt="Processed Image"
              className="w-full h-auto"
            />
          </div>
        </div>
      )}
    </div>
  );
}

export default Home;
