import React, { useState, useRef } from "react";
import image3 from "../../../public/assets/image10.png";
import Image from "next/image";
import { useRouter } from "next/navigation";
import Niv from "@/components/niv";
import Swal from "sweetalert2";
import SpeechToText from "../../components/SpeechToText";
import { auth, firestore } from "../../../firebaseconfig";
import { collection, addDoc, doc, setDoc } from "firebase/firestore";
import axios from "axios";

function Home() {
  const router = useRouter();
  const [textAreaContent, setTextAreaContent] = useState(""); // State to store the text area content
  const [isListening, setIsListening] = useState(false);
  const [aiResponse, setAIResponse] = useState("");
  const speechToTextRef = useRef<any>(null);
  const [voiceResponse, setVoiceResponse] = useState("");

  // To track if the last update was from transcription to avoid duplicate appends
  const [lastTranscript, setLastTranscript] = useState("");

  // Handle transcription updates
  const handleTranscript = (text: string) => {
    // Only append if the text has changed, preventing duplicate appends
    if (text !== lastTranscript) {
      setTextAreaContent((prevContent) => prevContent + text);
      setLastTranscript(text); // Update the last transcription to avoid duplicates
    }
  };

  // Handle stopping the transcription
  const handleStopListening = () => {
    Swal.fire(
      "Speech Recognition Stopped",
      "You can now review your text.",
      "info"
    );
  };

  const handleSubmit = async () => {
    if (!textAreaContent.trim()) {
      Swal.fire(
        "Error",
        "Please enter or speak some text before submitting.",
        "error"
      );
      return;
    }

    const userEmail = localStorage.getItem("user");
    if (!userEmail) {
      Swal.fire("Error", "User email not found. Please log in.", "error");
      return;
    }

    try {
      Swal.fire({
        title: "Uploading...",
        text: "Please wait while we upload your file.",
        icon: "info",
        allowOutsideClick: false,
        didOpen: () => {
          Swal.showLoading();
        },
      });
      const response = await axios.post(
        "https://us-central1-regal-campus-448011-c9.cloudfunctions.net/fakenewsEnglish",
        { text: textAreaContent }
      );

      const apiResult = response.data.result;
      console.log("API Result:", apiResult);

      const userDocRef = collection(firestore, "EnglishNews");
      const docRef = doc(userDocRef, userEmail);

      await setDoc(docRef, {
        inputText: textAreaContent,
        result: apiResult,
        timestamp: new Date(),
      });

      setAIResponse(apiResult);
      Swal.fire("Success", "The text was processed successfully!", "success");
    } catch (error) {
      console.error("Error submitting text:", error);
      Swal.fire(
        "Error",
        "Failed to process the text. Please try again.",
        "error"
      );
    }
  };

  const handleClear = () => {
    setTextAreaContent("");
    setAIResponse("");
    setVoiceResponse("");
    setLastTranscript(""); // Reset the transcription tracking
    if (speechToTextRef.current) {
      speechToTextRef.current.clearTranscript();
    }
    window.location.reload();
    console.log("Clearing data...");
    Swal.fire("Cleared", "The text and AI result have been cleared.", "info");
  };

  return (
    <div>
      <Niv />
      <div className="flex p-4">
        <div className="flex flex-col lg:flex-row w-full max-w-8xl">
          <div className="w-1/2 flex flex-col justify-center px-8 py-12 mt-5">
            <h2 className="text-orange-500 text-3xl font-bold mb-8">
              English Text and Voice Verification: Detect Authenticity
            </h2>

            <b className="text-1.5xl me-5">
              Upload text or voice to verify if it's real or fabricated
            </b>

            <div className="card w-96 flex-grow me-3 relative">
              <p>
                "Uncertain whether an English text or voice recording is
                authentic? Upload your content, and our system will
                analyze it for any signs of manipulation or fabrication. Using
                advanced natural language processing and voice recognition
                technology, we’ll determine if the text is genuine or fake and
                whether the voice recording has been altered or generated by AI.
                Ensure that the information you receive or share is reliable and
                accurate."
              </p>
            </div>
          </div>
          <div className="flex justify-center lg:w-1/2 w-full mb-8 lg:mb-0">
            <div>
              <textarea
                className="textarea border-orange-500 bg-orange-100 border-[3px] mt-5 h-[300px] w-[100vh]"
                value={textAreaContent} // Use state value
                onChange={(e) => setTextAreaContent(e.target.value)} // Allow manual input
                placeholder="Speak or type text here..."
              ></textarea>

              <div className="flex items-center space-x-3 mt-4">
                <SpeechToText
                  ref={speechToTextRef}
                  onTranscript={handleTranscript} // Handle transcription
                  onStopListening={handleStopListening}
                  onVoiceResponse={(response) => setVoiceResponse(response)}
                  onListeningChange={setIsListening}
                />

                <button
                  className="bg-blue-900 text-white font-bold py-2 px-4 rounded"
                  onClick={handleSubmit}
                >
                  Upload Text
                </button>
                <button
                  className="bg-red-600 text-white font-bold py-2 px-4 rounded"
                  onClick={handleClear}
                >
                  Clear
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="card border border-orange-500 bg-orange-100 border-[3px] rounded-box h-[150px] flex-grow m-5 p-5">
        <b className="text-1.5xl">"AI Verifies Results:"</b>
        <div className="flex justify-between mt-3 gap-4">
          <div className="border border-gray-400 bg-white rounded-md p-2 w-1/2 text-center">
            <b>Voice AI Response:</b>
            <div>{voiceResponse || "Awaiting voice analysis..."}</div>
          </div>
          <div className="border border-gray-400 bg-white rounded-md p-2 w-1/2 text-center">
            <b>AI Response:</b>
            <div>{aiResponse || "Awaiting analysis..."}</div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default Home;
